### PR TITLE
fix: card size in company page

### LINKED ISSUE #109: bug: Correction in the size of cards in the company page.
### Description

There is a card which is smaller in size in comparison to the other cards in the company page.

Screenshot (80)

### PR DESCRIPTION
**Pull request by Asmi-1**
fixes #109 by adding height and width to the image

### CODE REVIEW

File: pages/company/components/Hero.tsx [hunk 1]
```diff
@@ -50,7 +51,12 @@ export const Hero: FC<IHero> = ({}) => {
 						(img, index) => (
 							<SwiperSlide key={index}>
 								<Box sx={{ userSelect: "none" }}>
-									<Image src={img} alt={`Hero Slider Image ${index + 1}`} />
+									<Image
+										src={img}
+										alt={`Hero Slider Image ${index + 1}`}
+										height={330}
+										width={330}
```
Comment (ashuvssut) [inline pages/company/components/Hero.tsx:58]: ### **BAD STYLING**

This image is not responsive at all. For different screen sizes, images should be free to have different sizes. 

**By applying those absolute sizes, you are restricting responsiveness.**

Comment (ashuvssut) [reply pages/company/components/Hero.tsx]: [This were the required changes](https://github.com/WalkingPal/walking-pal-web/pull/111/commits/5dd8967064183114ad6a89aa1ab6cdb33a537bd8) that you should have applied!

Learn using devtools
