### PR TITLE
fix(home): added react intersection observer

### LINKED ISSUE #21: Start the Youtube Video in home page only when it appears inside viewport
In home page, the YT video starts up when the page loads. this is not desired

use [JS intersection observers](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to detect when the youtube video appears inside the viewport. when the youtube video appears inside viewport, trigger/start playing the video

Use can use this package https://www.npmjs.com/package/react-intersection-observer
or create you own custom react hook

### PR DESCRIPTION
**Pull request by utsav82**
YT video on homepage started as soon as page loaded.
Used react intersection observer to detect when the video enters viewport and then triggering play accordingly.

fixes #21

### CODE REVIEW

**Comment by ashuvssut** [comment]
Nicely done!

Do you think you can make a global component named `SlideIn`. This component will take a `ReactNode` as `children`. whenever that `ReactNode` enters viewport, it will come sliding-in from bottom. also when it exits the viewport, it will go sliding-out of the viewport

we need to make the trigger viewport smaller... about 100px from top and bottom... maybe we use `rootMargin` property to do this... i forgot... but, this make the viewport trigger area smaller so that the sweeping in effect triggers after the ReactNode has entered/exited 100px from bottom/top respectively.

If you wanna do this, you can open up a issue for this

File: pages/home/Home.tsx [hunk 1]
```diff
@@ -38,22 +40,24 @@ export const Home: NextPage = () => {
...
-							/>
-						)}
-					</Box>
+					<InView as="div" onChange={(inView, entry) => setYplay(inView)}>
+						<Box display="flex" justifyContent="center" mx="4vw" my={4}>
+							{width && (
+								<ReactPlayer
+									width={width < 1200 ? width - 0.08 * width : 1200}
+									height={width < 1200 ? (width - 0.08 * width) * 0.5625 : 675}
+									playIcon={<Play />} // TODO : Doesnt work. ref: https://stackoverflow.com/q/69132970/12872199
```
Comment (ashuvssut) [inline pages/home/Home.tsx:49]: you can open up your next issue for this issue too ;)

**Review by ashuvssut — APPROVED** [review]

**Comment by ashuvssut** [comment]
Nicely done!

*Another idea for next issue*
Do you think you can make a global component named SlideIn. This component will take a ReactNode as children. whenever that ReactNode enters viewport, it will come sliding-in from bottom. also when it exits the viewport, it will go sliding-out of the viewport

we need to make the trigger viewport smaller... about 100px from top and bottom... maybe we use rootMargin property to do this... i forgot... but, this make the viewport trigger area smaller so that the sweeping in effect triggers after the ReactNode has entered/exited 100px from bottom/top respectively.

If you wanna do this, you can open up a issue for this
